config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [:new, :create, :show]
  # Defines the root path route ("/")
  root "users#new"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP.freeze
  PASSWORD_REGEX = /\A
    (?=.*[[:^alnum:]]) # Must contain at least one special character
    (?=.*[a-z])        # Must contain at least one lowercase letter
    (?=.*[A-Z])        # Must contain at least one uppercase letter
    (?=.*\d)           # Must contain at least one digit
  /x

  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX, message: I18n.t('user.errors.email') }
  validates :password, presence: true, length: { minimum: 8 },
                       format: { with: PASSWORD_REGEX, message: I18n.t('user.errors.password') }
  validates :password_confirmation, presence: true, if: -> { password.present? }

  private_constant :EMAIL_REGEX, :PASSWORD_REGEX
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
# frozen_string_literal: true

module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |_exception|
      render 'shared/not_found', status: :not_found
    end

    rescue_from ActionController::ParameterMissing do |exception|
      flash.now[:alert] = "Required parameters are missing: #{exception.param}"
      render :new
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarkTestChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="alert <%= 'alert-success' if type == 'notice' %> <%= 'alert-danger' if type == 'alert' %>">
        <%= message %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/shared/not_found.html.erb
<div class='container text-center text-light' style='background: #3B3B99;'>
  <h1>404</h1>
  <h3>Page not found</h3>
  <p>oops! the page you are looking for doesn't exists. It might have been moved or deleted.</p>
  <div class='error-actions'>
    <a href='/' class='btn btn-outline-dark text-light'>Back To Home </a>
  </div>
</div>

app/views/users/new.html.erb
<section class="vh-100 bg-image"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5" data-controller="user">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

              <%= form_with model: @user, url: users_path, local: true, data: { controller: "user", action: "submit->user#submit" } do |form| %>
                <div class="form-outline mb-4">
                  <%= form.label :email, "Email", class: 'form-label', for: "email" %>
                  <%= form.email_field :email, id: "email", class: 'form-control form-control-lg', placeholder: "Enter email", data: { user_target: 'email', action: 'keyup->user#validateEmail' } %>
                </div>

                <div class="form-outline mb-4">
                  <%= form.label :password %>
                  <%= form.password_field :password, class: 'form-control form-control-lg', data: { user_target: 'input', action: 'keyup->user#validate' } %>
                </div>

                <div class="form-outline mb-4">
                  <%= form.label :password_confirmation, "Confirm Password" %>
                  <%= form.password_field :password_confirmation, class: 'form-control form-control-lg', data: { user_target: 'passwordConfirmation', action: 'keyup->user#validatePasswordConfirmation' } %>
                </div>

                <% if @user.errors.any? %>
                  <ul class='text-danger'>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                <% else %>
                  <div id="feedback" data-user-target="feedback"></div>
                <% end %>

                <%= form.submit 'Register', class: 'btn btn-success btn-block btn-lg gradient-custom-4 text-body' %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<h1>User Details</h1>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Email</h5>
    <p class="card-text"><%= @user.email %></p>
    
    <%= link_to 'Add New', new_user_path, class: 'btn btn-secondary' %>
  </div>
</div>